tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/services'
tap 'kreuzwerker/taps'
tap 'siderolabs/tap'
tap 'superfly/tap'

brew 'ansible'
brew 'argocd'
brew 'cilium-cli'
brew 'crane'
brew 'ffmpeg'
brew 'flyctl'
brew 'gh'
brew 'git'
brew 'git-crypt'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'go'
brew 'helm'
brew 'httpie'
brew 'hubble'
brew 'hugo'
brew 'iperf'
brew 'jq'
brew 'k9s'
brew 'kubernetes-cli'
brew 'kubeshark'
brew 'kustomize'
brew 'mas'
brew 'mtr'
brew 'neovim'
brew 'nmap'
brew 'pdfgrep'
brew 'python'
brew 'rclone'
brew 'sqlite'
brew 'sshuttle'
brew 'terraform'
brew 'tmux'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'wireguard-tools'
brew 'yamllint'
brew 'youtube-dl'
brew 'yt-dlp'
brew 'kreuzwerker/taps/m1-terraform-provider-helper'
brew 'siderolabs/tap/talosctl'

cask '1password'
cask '1password-cli'
cask 'calibre'
cask 'fantastical'
cask 'handbrake'
cask 'imageoptim'
cask 'istat-menus'
cask 'iterm2'
cask 'launchbar'
cask 'little-snitch'
cask 'netnewswire'
cask 'obsidian'
cask 'powershell'
cask 'rectangle-pro'
cask 'safari-technology-preview'
cask 'sourcetree'
cask 'steam'
cask 'suspicious-package'
cask 'tunnelblick'
cask 'visual-studio-code'
cask 'vlc'
cask 'wezterm'
cask 'wireshark'

# Fonts
cask 'font-cascadia-code'
cask 'font-ibm-plex-mono'
cask 'font-lato'
cask 'font-monaspace'
cask 'font-sf-mono'
cask 'font-sf-pro'
cask 'font-source-code-pro'
cask 'font-ubuntu'
cask 'font-ubuntu-mono'
cask 'font-ubuntu-sans'
cask 'font-ubuntu-sans-mono'

# App Store
## mas search <name> to find id
mas '1Blocker', id: 1365531024
mas '1Password for Safari', id: 1569813296
mas 'Bear', id: 1091189122
mas 'GIF Brewery 3', id: 1081413713
mas 'Ivory', id: 6444602274
mas 'Keystone', id: 409183695
mas 'Microsoft Remote Desktop 10', id: 1295203466
mas 'Numbers', id: 361304891
mas 'Pages', id: 361309726
mas 'Remote Desktop', id: 409907375
mas 'Tailscale', id: 1475387142
mas 'WiFi Explorer', id: 494803304
